#!/sbin/sh
#
# HP-UX 10.20 IP aliasing startup/shutdown script.
# Written by Greg Baker (gregb@ifost.org.au)
#

# In /etc/rc.config.d/ipalias,  the following variables 
# IFALIAS_IFACE[i]:    the interface to add the alias to
# IFALIAS_ADDRESS[i]:  the IP address to alias
# IFALIAS_NETMASK[i]:   the subnet mask to use  (optional)

# Allowed exit values:
#	0 = success; causes "OK" to show up in checklist.
#	1 = failure; causes "FAIL" to show up in checklist.
#	2 = skip; causes "N/A" to show up in the checklist.
#           Use this value if execution of this script is overridden
#	    by the use of a control variable, or if this script is not
#	    appropriate to execute for some other reason.
#       3 = reboot; causes the system to be rebooted after execution.

# Input and output:
#	stdin is redirected from /dev/null
#
#	stdout and stderr are redirected to the /etc/rc.log file
#	during checklist mode, or to the console in raw mode.

PATH=/usr/sbin:/usr/bin:/sbin:/usr/contrib/bin
export PATH

# NOTE: If your script executes in run state 0 or state 1, then /usr might
#	not be available.  Do not attempt to access commands or files in
#	/usr unless your script executes in run state 2 or greater.  Other
#	file systems typically not mounted until run state 2 include /var
#	and /opt.

rval=0

# Check the exit value of a command run by this script.  If non-zero, the
# exit code is echoed to the log file and the return value of this script
# is set to indicate failure.

set_return() {
	x=$?
	if [ $x -ne 0 ]; then
		echo "EXIT CODE: $x"
		rval=1	# script FAILed
	fi
}


case $1 in
'start_msg')
	echo "Adding IP aliases"
	;;

'stop_msg')
	echo "Removing IP aliases"
	;;

'start')

	# source the system configuration variables
	if [ -f /etc/rc.config ] ; then
		. /etc/rc.config
	else
		echo "ERROR: /etc/rc.config defaults file MISSING"
	fi
        X=0
        while [ "${IFALIAS_IFACE[$X]}" != "" ]
        do
           if [ "${IFALIAS_NETMASK[$X]}" = "" ]
           then
              ifalias ${IFALIAS_IFACE[$X]} add ${IFALIAS_ADDRESS[$X]}
           else
              ifalias ${IFALIAS_IFACE[$X]} addmask ${IFALIAS_NETMASK[$X]} ${IFALIAS_ADDRESS[$X]}
           fi
           let X=X+1
        done
	;;

'stop')
	# source the system configuration variables
	if [ -f /etc/rc.config ] ; then
		. /etc/rc.config
	else
		echo "ERROR: /etc/rc.config defaults file MISSING"
	fi
        X=0
        while [ "${IFALIAS_IFACE[$X]}" != "" ]
        do
           ifalias ${IFALIAS_IFACE[$X]} del ${IFALIAS_ADDRESS[$X]}
           let X=X+1
        done

	;;

*)
	echo "usage: $0 {start|stop|start_msg|stop_msg}"
	rval=1
	;;
esac

exit $rval
